version: 2.0

python:
  version: "3.9"
  install:
    - requirements: requirements/requirements.min.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: another/package
  system_packages: true

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false